# Generated by Django 6.0.6 on 2026-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_id', models.CharField(default='button_1', max_length=50)),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='buttondata',
            index=models.Index(fields=['button_id', 'is_latest'], name='mainapp_but_button__247a08_idx'),
        ),
        migrations.AddIndex(
            model_name='buttondata',
            index=models.Index(fields=['timestamp'], name='mainapp_but_timesta_61b038_idx'),
        ),
    ]
